name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

permissions:
  contents: read   # remove id-token

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          
  "clientId": "b4a0f6bf-46f5-441d-9d7c-9d1a7f7e35c1",
  "subscriptionId": "c51bef20-47a6-4ddc-b7dc-738209997e1d",
  "tenantId": "5749d006-e531-436d-943c-f3883e5a64b8"


          

      - name: Login to Azure Container Registry
        run: az acr login --name imageregistryacr

      - name: Build Docker image
        run: docker build -t todo-ui:v1 .

      - name: Tag Docker image for ACR
        run: docker tag todo-ui:v1 imageregistryacr.azurecr.io/todo-ui:v1

      - name: Push Docker image to ACR
        run: docker push imageregistryacr.azurecr.io/todo-ui:v1
