name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

permissions:
  contents: read   # remove id-token

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: service-principal

      - name: Login to Azure Container Registry
        run: az acr login --name imageregistryacr

      - name: Build Docker image
        run: docker build -t todo-ui:v1 .

      - name: Tag Docker image for ACR
        run: docker tag todo-ui:v1 imageregistryacr.azurecr.io/todo-ui:v1

      - name: Push Docker image to ACR
        run: docker push imageregistryacr.azurecr.io/todo-ui:v1
